model:
  downsample_rate: 3
  hidden_dim: 768
  num_layers: 6
  attention_head: 12
  intermediate_dim: 3072
  act_fn: "gelu"
  hidden_dropout_prob: 0.1
  attention_prob_dropout_prob: 0.1
  init_range: 0.02
  norm_eps: 1.0e-12



